cmake_minimum_required(VERSION 3.18)
project(tei_torch LANGUAGES CXX)
find_package(Torch 2.14.1 EXACT REQUIRED)
add_library(tei_torch SHARED bridge.cpp)
target_compile_features(tei_torch PRIVATE cxx_std_20)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
target_link_libraries(tei_torch PRIVATE "${TORCH_LIBRARIES}")
set_target_properties(tei_torch PROPERTIES INSTALL_RPATH "${TORCH_INSTALL_PREFIX}/lib;$ORIGIN")
install(TARGETS tei_torch LIBRARY DESTINATION lib RUNTIME DESTINATION bin)
