use crate::layers::{HiddenAct, RopeScaling};
use serde::Deserialize;

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct MistralConfig {
    pub vocab_size: usize,
    pub hidden_size: usize,
    pub intermediate_size: usize,
    pub num_hidden_layers: usize,
    pub num_attention_heads: usize,
    pub head_dim: Option<usize>,
    pub num_key_value_heads: usize,
    pub hidden_act: HiddenAct,
    pub max_position_embeddings: usize,
    pub initializer_range: f64,
    pub rms_norm_eps: f32,
    pub model_type: Option<String>,
    pub rope_theta: f32,
    pub sliding_window: Option<usize>,
    pub rope_scaling: Option<RopeScaling>,
    #[serde(default)]
    pub use_bidirectional_attention: bool,
    pub is_causal: Option<bool>,
    pub rope_parameters: Option<MinistralRope>,
}

impl MistralConfig {
    pub fn head_dim(&self) -> usize {
        self.head_dim
            .unwrap_or(self.hidden_size / self.num_attention_heads)
    }

    pub fn bidirectional(&self) -> bool {
        self.is_causal
            .map(|causal| !causal)
            .unwrap_or(self.use_bidirectional_attention)
    }
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct MinistralRope {
    pub rope_type: String,
    pub rope_theta: f32,
    pub factor: f32,
    pub beta_fast: f64,
    pub beta_slow: f64,
    pub original_max_position_embeddings: usize,
    pub mscale: f64,
    pub mscale_all_dim: f64,
    pub llama_4_scaling_beta: f32,
}

impl MinistralRope {
    // `apply_yarn_scaling` in Nemotron's checkpoint is vLLM compatibility metadata;
    // Transformers applies YaRN using these parameters regardless of that flag.
    pub fn frequencies(&self, dim: usize) -> candle::Result<(Vec<f32>, f64)> {
        if self.rope_type != "yarn"
            || self.factor < 1.0
            || self.rope_theta <= 1.0
            || self.original_max_position_embeddings == 0
            || self.beta_fast <= 0.0
            || self.beta_slow <= 0.0
            || dim == 0
            || !dim.is_multiple_of(2)
        {
            candle::bail!("Unsupported Ministral RoPE parameters");
        }
        let correction = |rotations: f64| {
            dim as f64
                * (self.original_max_position_embeddings as f64
                    / (rotations * 2.0 * std::f64::consts::PI))
                    .ln()
                / (2.0 * (self.rope_theta as f64).ln())
        };
        let low = correction(self.beta_fast).floor().max(0.0) as f32;
        let mut high = correction(self.beta_slow).ceil().min((dim - 1) as f64) as f32;
        if low == high {
            high += 0.001;
        }
        let inv = (0..dim / 2)
            .map(|i| {
                let freq = self.rope_theta.powf((2 * i) as f32 / dim as f32);
                let extrapolation = 1.0 - ((i as f32 - low) / (high - low)).clamp(0.0, 1.0);
                (1.0 / (self.factor * freq)) * (1.0 - extrapolation) + (1.0 / freq) * extrapolation
            })
            .collect();
        let mscale = |m: f64| 1.0 + 0.1 * m * (self.factor as f64).ln();
        let scale = if self.mscale != 0.0 && self.mscale_all_dim != 0.0 {
            mscale(self.mscale) / mscale(self.mscale_all_dim)
        } else {
            mscale(1.0)
        };
        Ok((inv, scale))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nemotron_yarn_matches_transformers() -> candle::Result<()> {
        let rope = MinistralRope {
            rope_type: "yarn".into(),
            rope_theta: 1_000_000.0,
            factor: 16.0,
            beta_fast: 32.0,
            beta_slow: 1.0,
            original_max_position_embeddings: 16384,
            mscale: 1.0,
            mscale_all_dim: 1.0,
            llama_4_scaling_beta: 0.1,
        };
        let (freqs, scale) = rope.frequencies(128)?;
        // Independently generated by Transformers' Ministral3RotaryEmbedding.
        for (index, expected) in [
            (0, 1.0),
            (12, 0.07498941570520401),
            (24, 0.004382954444736242),
            (32, 0.0003382352879270911),
            (48, 1.9764233911701012e-6),
            (63, 7.75586102008674e-8),
        ] {
            assert!((freqs[index] as f64 / expected - 1.0).abs() < 1e-6);
        }
        assert_eq!(scale, 1.0);
        Ok(())
    }
}
