[package]
name = "text-embeddings-backend"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true

[dependencies]
clap = { workspace = true, optional = true }
hf-hub = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
text-embeddings-backend-core = { path = "core" }
text-embeddings-backend-python = { path = "python", optional = true }
text-embeddings-backend-candle = { path = "candle", optional = true }
tokio = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }

[features]
prefix-cache-paged = ["fa4", "text-embeddings-backend-candle?/prefix-cache-paged"]
experimental-fp8 = ["candle", "text-embeddings-backend-candle/experimental-fp8"]
experimental-fa4 = ["fa4"]
fa4 = ["text-embeddings-backend-candle?/fa4"]
clap = ["dep:clap", "text-embeddings-backend-core/clap"]
python = ["dep:text-embeddings-backend-python"]
candle = ["dep:text-embeddings-backend-candle"]
cuda = ["text-embeddings-backend-candle?/cuda"]
cuda-static-linking = ["text-embeddings-backend-candle?/cuda-static-linking"]
cuda-dynamic-linking = ["text-embeddings-backend-candle?/cuda-dynamic-linking"]
metal = ["text-embeddings-backend-candle?/metal"]
mkl = ["text-embeddings-backend-candle?/mkl"]
accelerate = ["text-embeddings-backend-candle?/accelerate"]
flash-attn = ["text-embeddings-backend-candle?/flash-attn"]
flash-attn-v1 = ["text-embeddings-backend-candle?/flash-attn-v1"]

experimental-deberta = ["text-embeddings-backend-candle?/experimental-deberta"]
