#![cfg(feature = "flash-attn")]

use anyhow::Result;
use serde::Deserialize;
use std::path::PathBuf;
use text_embeddings_backend_candle::CandleBackend;
use text_embeddings_backend_core::{Backend, Batch, Embedding, ModelType, Pool};

#[derive(Deserialize)]
struct Reference {
    sequences: Vec<Vec<u32>>,
    pooled: Vec<Vec<f32>>,
    raw: Vec<Vec<Vec<f32>>>,
    projected: Vec<Vec<f32>>,
}

fn batch(sequences: &[Vec<u32>], raw: bool) -> Batch {
    let input_ids: Vec<_> = sequences.iter().flatten().copied().collect();
    let mut cumulative = vec![0];
    for sequence in sequences {
        cumulative.push(cumulative.last().unwrap() + sequence.len() as u32);
    }
    Batch {
        token_type_ids: vec![0; input_ids.len()],
        input_ids,
        position_ids: sequences.iter().flat_map(|s| 0..s.len() as u32).collect(),
        cumulative_seq_lengths: cumulative,
        max_length: sequences.iter().map(Vec::len).max().unwrap() as u32,
        pooled_indices: if raw {
            vec![]
        } else {
            (0..sequences.len() as u32).collect()
        },
        raw_indices: if raw {
            (0..sequences.len() as u32).rev().collect()
        } else {
            vec![]
        },
        compact_input_ids: None,
        compact_position_ids: None,
        scatter_unfold: None,
        fold_gather: None,
        tokens: vec![],
        offsets: vec![],
    }
}

fn compare(actual: &[f32], expected: &[f32]) {
    assert_eq!(actual.len(), expected.len());
    assert!(actual.iter().all(|x| x.is_finite()));
    let dot: f64 = actual
        .iter()
        .zip(expected)
        .map(|(&a, &b)| a as f64 * b as f64)
        .sum();
    let norm = |v: &[f32]| v.iter().map(|&x| (x as f64).powi(2)).sum::<f64>().sqrt();
    let cosine = dot / (norm(actual) * norm(expected));
    assert!(cosine > 0.9999, "reference cosine {cosine}");
    let delta = actual
        .iter()
        .zip(expected)
        .map(|(&a, &b)| (a as f64 - b as f64).powi(2))
        .sum::<f64>()
        .sqrt();
    assert!(
        delta / norm(expected) < 0.02,
        "relative L2 error {}",
        delta / norm(expected)
    );
}

#[test]
#[ignore = "requires CUDA and EMBEDDINGGEMMA_FIXTURE_DIR generated by the reference script"]
fn ragged_matches_transformers_and_rejects_other_dtypes() -> Result<()> {
    let root = PathBuf::from(std::env::var("EMBEDDINGGEMMA_FIXTURE_DIR")?);
    let references: Vec<Reference> =
        serde_json::from_slice(&std::fs::read(root.join("reference.json"))?)?;
    let backend = CandleBackend::new(
        &root,
        "bfloat16".into(),
        ModelType::Embedding(Pool::Mean),
        None,
        0,
    )?;
    let projected_backend = CandleBackend::new(
        &root,
        "bfloat16".into(),
        ModelType::Embedding(Pool::Mean),
        Some(vec!["2_Dense".into(), "3_Dense".into()]),
        0,
    )?;
    for case in references {
        let pooled = backend.embed(batch(&case.sequences, false))?;
        for (index, expected) in case.pooled.iter().enumerate() {
            match &pooled[&index] {
                Embedding::Pooled(actual) => compare(actual, expected),
                _ => panic!("expected pooled embeddings"),
            }
        }
        // Exercise subset selection and mixed raw/pooled output in the same batch.
        let mut mixed = batch(&case.sequences, false);
        let last = case.sequences.len() - 1;
        mixed.pooled_indices = vec![last as u32];
        if last > 0 {
            mixed.raw_indices = vec![0];
        }
        let projected = projected_backend.embed(mixed)?;
        match &projected[&last] {
            Embedding::Pooled(actual) => compare(actual, &case.projected[last]),
            _ => panic!("expected projected embedding"),
        }
        if last > 0 {
            match &projected[&0] {
                Embedding::All(actual) => {
                    assert_eq!(actual.len(), case.raw[0].len());
                    for (actual, expected) in actual.iter().zip(&case.raw[0]) {
                        compare(actual, expected);
                    }
                }
                _ => panic!("expected unprojected token embeddings"),
            }
        }
        let raw = backend.embed(batch(&case.sequences, true))?;
        for (index, expected) in case.raw.iter().enumerate() {
            match &raw[&index] {
                Embedding::All(actual) => {
                    assert_eq!(actual.len(), expected.len());
                    for (actual, expected) in actual.iter().zip(expected) {
                        compare(actual, expected);
                    }
                }
                _ => panic!("expected token embeddings"),
            }
        }
    }
    for dtype in ["float32", "float16"] {
        let error = match CandleBackend::new(
            &root,
            dtype.into(),
            ModelType::Embedding(Pool::Mean),
            None,
            0,
        ) {
            Ok(_) => panic!("unsupported dtype {dtype} was accepted"),
            Err(error) => error.to_string(),
        };
        assert!(error.contains("requires CUDA bfloat16"), "{error}");
    }
    Ok(())
}
